services:
  caddy:
    networks:
      - pi
    container_name: caddy
    image: caddy:2.11-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./srv:/srv
      - ../state-machine/dist/:/usr/share/caddy/host/chain:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  pi:
    external: true
